kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: observability
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Grafana
  - containerPort: 30300
    hostPort: 3000
    protocol: TCP
  # Prometheus
  - containerPort: 30900
    hostPort: 9090
    protocol: TCP
  # Jaeger
  - containerPort: 31686
    hostPort: 16686
    protocol: TCP
  # Alertmanager
  - containerPort: 30903
    hostPort: 9093
    protocol: TCP
- role: worker
- role: worker