global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'sample-nodejs-app'
    static_configs:
      - targets: ['sample-app:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s